export const ACTION = {
  NEWTAB: "NewTab",
  ACTIVATE_TAB: "ActivateTab",
  OPEN_URL: "OpenUrl",
  CLOSE_TAB: "CloseTab",
  GO_BACK: "GoBack",
  RELOAD_PAGE: "ReloadPage",
  // CLICK: "Click",
  // PRESS_KEY: "PressKey",
  // TYPE_TEXT: "TypeText",
  // ELEMENT_EXISTS: "ElementExists",
  // GET_URL: "GetUrl",
  // GET_TEXT: "GetText",
  // GET_VALUE: "GetValue",
  // GET_ATTRIBUTE: "GetAttribute",
  // SELECT_DROPDOWN: "SelectDropdown",
  // RANDOM: "Random",
  // FILE_UPLOAD: "FileUpload",
  // HTTP: "Http",
  // WRITE_FILE: "WriteFile",
  // SET_VARIABLE: "SetVariable",
  // COOKIES: "Cookies",
} as const;
export type ActionType = (typeof ACTION)[keyof typeof ACTION];
